version: 2
jobs:
  check_and_deploy:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run:
          name: Install td client and setup
          command: |
            gem install td
            td apikey:set ${TD_APIKEY}
            echo Y | td wf
      - run: td wf check
      - run: td wf push kawa_test

workflows:
  version: 2
  check_and_deploy:
    filters:
      branches:
        only:
          - production
